services:
  database:
    image: mariadb:10.4
    restart: always
    container_name: '<<APP_NAME>>-database'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wackarlompe
    volumes:
      - database-volume:/var/lib/mysql

volumes:
  database-volume:
